F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-67.58, -39.03],[-67.58, -39.03]]},"properties": {"type":"T", "season":1977, "year":1977, "month":11, "day":-99, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-62.86, -31.41],[-62.8, -31.36]]},"properties": {"type":"T", "season":1977, "year":1977, "month":12, "day":4, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":150, "length":7, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":"There seems to be a duplicate list item, one of which gives 150 metres of width, while the other gives 500 metres."}});
F3_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-63.45, -31.75],[-63.24, -31.55]]},"properties": {"type":"T", "season":1977, "year":1977, "month":12, "day":4, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"3", "width":4000, "length":30, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});
F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-62.99, -38.3],[-62.97, -38.3]]},"properties": {"type":"T", "season":1977, "year":1977, "month":12, "day":4, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":250, "length":2.5, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-65.95, -39.19],[-65.95, -39.19]]},"properties": {"type":"T", "season":1977, "year":1978, "month":1, "day":9, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F0_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-62.1, -32.69],[-62.1, -32.69]]},"properties": {"type":"T", "season":1977, "year":1978, "month":1, "day":12, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"0", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});
