FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-68.19, -16.47],[-68.19, -16.47]]},"properties": {"type":"T", "season":2024, "year":2024, "month":9, "day":20, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Opinión","https://www.opinion.com.bo/articulo/pais/tornado-azota-laja-vientos-huracanados-impactan-sena/20240925000007956449.html"]], "locerror":2.5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-67.64, -37.34],[-67.64, -37.34]]},"properties": {"type":"T", "season":2024, "year":2024, "month":10, "day":16, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Los Andes","https://www.losandes.com.ar/sociedad/viento-lluvias-granizo-y-un-tornado-en-la-pampa"],["La Tecla Mar del Plata","https://www.lateclamardelplata.com.ar/53272-un-tornado-en-la-pampa"]], "locerror":1, "comments":"Managed to locate the road in the video from source [2] (roughly south of the tornado), after which I placed the tornado roughly where it seemed to be in the video."}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-62.142, -32.665],[-62.142, -32.665]]},"properties": {"type":"T", "season":2024, "year":2024, "month":10, "day":22, "hour":15, "minute":0, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["<i>Ignacio Bergara | Meteorología</i> | YouTube (1:58)","https://www.youtube.com/watch?v=oj6eprR3lvU&t=118s"],["El Litoral","https://www.ellitoral.com/informacion-general/tornado-celular-santa-fe-cordoba-limite-marcos-juarez-alerta-amarilla-tormentas-fenomeno-meteorologico-videos-clima-smn_0_bBg2fS5LFh.html"],["<i>Tornados en Argentina</i> | Google My Maps","https://www.google.com/maps/d/u/0/viewer?mid=1miZM6oOopquzYHV6op98x6vzhEq3Dlw"]], "locerror":1, "comments":"Location based on video from sources [1] & [2]."}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-58.48, -32.46],[-58.48, -32.46]]},"properties": {"type":"T", "season":2024, "year":2024, "month":10, "day":25, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["<i>Ignacio Bergara | Meteorología</i> | YouTube (2:12)","https://www.youtube.com/watch?v=oj6eprR3lvU&t=132s"],["<i>Tornados en Argentina</i> | Google My Maps","https://www.google.com/maps/d/u/0/viewer?mid=1miZM6oOopquzYHV6op98x6vzhEq3Dlw"]], "locerror":2.5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-62.87, -35.77],[-62.87, -35.77]]},"properties": {"type":"T", "season":2024, "year":2024, "month":11, "day":24, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["<i>Ignacio Bergara | Meteorología</i> | YouTube (2:29)","https://www.youtube.com/watch?v=oj6eprR3lvU&t=149s"],["<i>Tornados en Argentina</i> | Google My Maps","https://www.google.com/maps/d/u/0/viewer?mid=1miZM6oOopquzYHV6op98x6vzhEq3Dlw"]], "locerror":10, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-56.78, -30.74],[-56.78, -30.74]]},"properties": {"type":"T", "season":2024, "year":2024, "month":12, "day":6, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["<i>Mataorología Uruguaya-ROU</i> | facebook","https://www.facebook.com/MeteorologiaDeLaRepublica/videos/1360748765100342/"]], "locerror":2.5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-65.76, -39.3],[-65.76, -39.3]]},"properties": {"type":"T", "season":2024, "year":2024, "month":12, "day":11, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["<i>Ignacio Bergara | Meteorología</i> | YouTube (3:02)","https://www.youtube.com/watch?v=oj6eprR3lvU&t=182s"]], "locerror":2.5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-58.25, -37.85],[-58.25, -37.85]]},"properties": {"type":"T", "season":2024, "year":2024, "month":12, "day":19, "hour":18, "minute":0, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["<i>Ignacio Bergara | Meteorología</i> | YouTube (3:12)","https://www.youtube.com/watch?v=oj6eprR3lvU&t=192s"]], "locerror":5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-60.07, -38.85],[-60.07, -38.85]]},"properties": {"type":"T", "season":2024, "year":2024, "month":12, "day":31, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["<i>Ignacio Bergara | Meteorología</i> | YouTube (3:50)","https://www.youtube.com/watch?v=oj6eprR3lvU&t=230s"]], "locerror":2.5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-63.666, -31.85],[-63.666, -31.85]]},"properties": {"type":"T", "season":2024, "year":2024, "month":12, "day":31, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":0, "injuries":3, "sources":[["<i>Vélez Sarsfield & Fenómenos</i> | YouTube","https://www.youtube.com/watch?v=I6W9k40WPhw&t=847s"],["Hoy Día Córdoba","https://hoydia.com.ar/sucesos/un-temporal-destrozo-un-hotel-en-oncativo-y-causo-tres-heridos/"]], "locerror":1, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-57.42, -37.63],[-57.42, -37.63]]},"properties": {"type":"T", "season":2024, "year":2025, "month":1, "day":1, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":0, "injuries":0, "sources":[["LV12","https://www.lv12.com.ar/tornado/impactante-tornado-mar-chiquita-el-temporal-que-azoto-buenos-aires-n171706"],["m1","https://www.minutouno.com/sociedad/un-tornado-mar-chiquita-genero-preocupacion-turistas-y-habitantes-n6098625"]], "locerror":5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-63.06, -35.07],[-63.06, -35.07]]},"properties": {"type":"T", "season":2024, "year":2025, "month":2, "day":23, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":0, "injuries":0, "sources":[["<i>DisasterUpdate</i> | reddit","https://web.archive.org/web/20250327174218/https://www.reddit.com/r/TornadoWatch/comments/1iz0bkg/a_tornado_southwest_of_general_villegas_argentina/"]], "locerror":10, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-55.73, -32.225],[-55.73, -32.225]]},"properties": {"type":"T", "season":2024, "year":2025, "month":3, "day":3, "hour":15, "minute":0, "timezone":"UYT", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":0, "injuries":0, "sources":[["Metsul","https://metsul.com/supercelula-de-tempestade-forma-grande-tornado-no-uruguai/"],["<i>Bella Unión Noticias</i> | facebook","https://www.facebook.com/BellaUnionNoticias/videos/tornado-en-tierra-al-sur-de-la-ciudad-de-tacuaremb%C3%B3-uruguayen-el-medio-del-campo/570827775990095/"]], "locerror":2.5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-53.7534, -27.2146],[-53.7429, -27.2189],[-53.7328, -27.2222]]},"properties": {"type":"T", "season":2024, "year":2025, "month":5, "day":9, "hour":13, "minute":24, "timezone":"BRT", "lang":"por", "windspeed":-99, "rating":"1", "width":-99, "length":2.2, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Rastros de Tornados no Brasil | Previsão Master","https://previsaomasters.com/rastros-tornados"]], "locerror":-99, "comments":""}});
F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-53.7199, -27.2236],[-53.6807, -27.2184]]},"properties": {"type":"T", "season":2024, "year":2025, "month":5, "day":9, "hour":13, "minute":30, "timezone":"BRT", "lang":"por", "windspeed":-99, "rating":"1", "width":-99, "length":3.9, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Rastros de Tornados no Brasil | Previsão Master","https://previsaomasters.com/rastros-tornados"]], "locerror":-99, "comments":""}});
F0_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-53.3042, -27.1354],[-53.27, -27.1352]]},"properties": {"type":"T", "season":2024, "year":2025, "month":5, "day":9, "hour":14, "minute":0, "timezone":"BRT", "lang":"por", "windspeed":-99, "rating":"0", "width":-99, "length":3.4, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Rastros de Tornados no Brasil | Previsão Master","https://previsaomasters.com/rastros-tornados"]], "locerror":-99, "comments":""}});
F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-53.2652, -27.1333],[-53.2623, -27.135],[-53.2583, -27.1376],[-53.2467, -27.144],[-53.242, -27.1461]]},"properties": {"type":"T", "season":2024, "year":2025, "month":5, "day":9, "hour":14, "minute":6, "timezone":"BRT", "lang":"por", "windspeed":-99, "rating":"1", "width":-99, "length":2.7, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Rastros de Tornados no Brasil | Previsão Master","https://previsaomasters.com/rastros-tornados"]], "locerror":-99, "comments":""}});
F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-53.2114, -27.1471],[-53.1899, -27.155],[-53.1741, -27.1591]]},"properties": {"type":"T", "season":2024, "year":2025, "month":5, "day":9, "hour":14, "minute":10, "timezone":"BRT", "lang":"por", "windspeed":-99, "rating":"1", "width":-99, "length":3.9, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Rastros de Tornados no Brasil | Previsão Master","https://previsaomasters.com/rastros-tornados"]], "locerror":-99, "comments":""}});
F2_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-52.5663, -27.3622],[-52.5497, -27.365],[-52.5205, -27.3649],[-52.5058, -27.3661]]},"properties": {"type":"T", "season":2024, "year":2025, "month":5, "day":9, "hour":14, "minute":50, "timezone":"BRT", "lang":"por", "windspeed":-99, "rating":"2", "width":500, "length":6, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Rastros de Tornados no Brasil | Previsão Master","https://previsaomasters.com/rastros-tornados"]], "locerror":-99, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-73.01, -41.26],[-72.97, -41.37]]},"properties": {"type":"T", "season":2024, "year":2025, "month":5, "day":25, "hour":15, "minute":30, "timezone":"CLT", "lang":"esp", "windspeed":-99, "rating":"1", "width":-99, "length":12.2, "duration":-99, "deaths":0, "injuries":19, "sources":[["emol.","https://www.emol.com/noticias/Nacional/2025/05/26/1167372/tornado-puerto-varas-balance-cogrid.html"],["Radio UCHILE","https://radio.uchile.cl/2025/06/03/puerto-varas-post-tornado-municipalidad-confirma-plan-de-reconstruccion-de-tres-etapas/"],["yahoo!news","https://www.yahoo.com/news/hundreds-homes-damaged-tornado-chile-183431838.html"],["infobae","https://www.infobae.com/peru/2025/05/25/tornado-en-chile-deja-sin-hogar-a-decenas-de-personas-alcalde-de-puerto-varas-reporta-graves-danos-en-la-ciudad/"],["CNN","https://www.cnnchile.com/pais/los-impactantes-registros-del-tornado-que-causo-graves-danos-en-puerto-varas/"]], "locerror":1, "comments":"I managed to locate where a video from source [4] was taken (41.3150°S, 72.9948°W, looking east). However, I could not find a damage path on Sentinel-2.<br><br> Movement direction taken from earth.nullschool.net, adjusted to match how it seemed to move in the aforementioned video."}});
