F2_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-63.879, -31.678],[-63.879, -31.678]]},"properties": {"type":"T", "season":1965, "year":1965, "month":9, "day":24, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"2", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 32)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F3_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-64.75, -33.41],[-64.69, -33.36]]},"properties": {"type":"T", "season":1965, "year":1965, "month":10, "day":22, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"3", "width":200, "length":8.5, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 32)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"],["ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA | Academia Nacional de Ciencias de Buenos Aires (Page 89)","https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf"]], "locerror":5, "comments":""}});

F2_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-59.09, -27.38],[-59.09, -27.38]]},"properties": {"type":"T", "season":1965, "year":1965, "month":12, "day":13, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"2", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 32)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"],["ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA | Academia Nacional de Ciencias de Buenos Aires (Page 89)","https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf"]], "locerror":5, "comments":""}});

F2_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-62.09, -31.43],[-62.09, -31.43]]},"properties": {"type":"T", "season":1965, "year":1966, "month":2, "day":16, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"2", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 32)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"],["ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA | Academia Nacional de Ciencias de Buenos Aires (Page 89)","https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-63.73, -32.43],[-63.73, -32.43]]},"properties": {"type":"T", "season":1965, "year":1966, "month":3, "day":1, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 32)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"],["ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA | Academia Nacional de Ciencias de Buenos Aires (Page 89)","https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-64.489, -31.101],[-64.482, -31.094]]},"properties": {"type":"T", "season":1965, "year":1966, "month":3, "day":4, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":150, "length":1, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 32)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"],["ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA | Academia Nacional de Ciencias de Buenos Aires (Page 89)","https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf"]], "locerror":5, "comments":""}});
