FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-51.06, -30.01],[-51.06, -30.01]]},"properties": {"type":"T", "season":1976, "year":1976, "month":-99, "day":-99, "hour":-99, "minute":-99, "timezone":"BRT", "lang":"por", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)","https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-65.91, -38.146],[-65.91, -38.146]]},"properties": {"type":"T", "season":1976, "year":1976, "month":12, "day":-99, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":25, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-64.54, -32.07],[-64.54, -32.07]]},"properties": {"type":"T", "season":1976, "year":1977, "month":2, "day":7, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":25, "length":10, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

FU_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-55.98, -31.72],[-55.98, -31.72]]},"properties": {"type":"T", "season":1976, "year":1977, "month":2, "day":8, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"U", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-66.17, -40.68],[-66.17, -40.68]]},"properties": {"type":"T", "season":1976, "year":1977, "month":3, "day":6, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":-99, "length":-99, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F1_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-58.54, -34.8],[-58.54, -34.8]]},"properties": {"type":"T", "season":1976, "year":1977, "month":3, "day":7, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"1", "width":50, "length":13, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});

F2_tornadoes.addData({"type": "Feature","geometry": {"type": "LineString","coordinates": [[-59.83, -25.33],[-59.53, -25.33]]},"properties": {"type":"T", "season":1976, "year":1977, "month":4, "day":7, "hour":-99, "minute":-99, "timezone":"ART", "lang":"esp", "windspeed":-99, "rating":"2", "width":2000, "length":30, "duration":-99, "deaths":-99, "injuries":-99, "sources":[["Climatología de los efectos de la convección severa en la República Argentina | Biblioteca Digital (Page 33)","https://web.archive.org/web/20210623181746/https://bibliotecadigital.exactas.uba.ar/download/tesis/tesis_n2211_AltingerdeSchwarzkopf.pdf"]], "locerror":5, "comments":""}});
