const tornado_2003_02_21_9999 = L.polyline([[-28.83, -49.63],[-28.83, -49.63]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2003/02/21</h2></th></tr> <tr><th>Start time</th><td>Sexta-feira, 21 fevereiro 2003</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 50)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2003_07_08_9999 = L.polyline([[-29.685, -53.818],[-29.685, -53.818]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2003/07/08</h2></th></tr> <tr><th>Start time</th><td>Tuesday, 8 July 2003</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2003_11_18_9999 = L.polyline([[-27.105, -52.626],[-27.105, -52.626]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2003/11/18</h2></th></tr> <tr><th>Start time</th><td>Tuesday, 18 November 2003</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2003_12_11_9999 = L.polyline([[-28.855, -51.281],[-28.855, -51.281]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2003/12/11</h2></th></tr> <tr><th>Start time</th><td>Thursday, 11 December 2003</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);