const tornado_2022_01_25_9999 = L.polyline([[-35.472, -69.584],[-35.472, -69.584]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2022/01/25</h2></th></tr> <tr><th>Start time</th><td>Martes, 25 enero 2022<sup>[1]</sup></td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://www.infobae.com/sociedad/2022/01/26/video-las-impactantes-imagenes-del-tornado-que-se-formo-en-mendoza/'>[1]:infobae</a>;<br> <a target='_blank' href='https://www.diariojornada.com.ar/318488/internacional/video_las_impactantes_imagenes_del_tornado_que_se_formo_en_mendoza'>[2]:Jordana</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2022_06_22_0200 = L.polyline([[-27.232, -52.021],[-27.232, -52.021]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2022/06/22</h2></th></tr> <tr><th>Start time</th><td><span class='source'>02:00,<sup title='Page 7'>[1]:7</sup></span> quarta-feira, 22 <span class='source'>June<sup>[2]</sup></span> 2022</td></tr> <tr><th>Rating</th><td>F1<sup>[1]</sup></td></tr> <tr><th>Width</th><td>100 m<sup title='Page 7'>[1]:7</sup></td></tr> <tr><th>Mortes</th><td>0<sup>[2]</sup></td></tr> <tr><th>Feridos</th><td>0<sup>[2]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://www.researchgate.net/publication/365203342_Tornadoes_Analysis_Concordia_Santa_Catarina_Southern_Brazil_2022_Season'>[1]:Tornadoes Analysis Concordia, Santa Catarina, Southern Brazil, 2022 Season. | ResearchGate</a>;<br> <a target='_blank' href='https://g1.globo.com/sc/santa-catarina/noticia/2022/06/28/defesa-civil-de-sc-confirma-passagem-de-tornado-com-rajadas-de-vento-acima-de-100-kmh.ghtml'>[2]:g1</a></td></tr> <tr><th>Comments</th><td>Source [1] must be downloaded by the reader in order to function as a source.</td></tr>"
).addTo(F1_tornadoes);
const tornado_2022_11_09_9999 = L.polyline([[-35.476, -69.580],[-35.476, -69.580]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2022/11/09</h2></th></tr> <tr><th>Start time</th><td>Miércoles, 9 noviembre 2022</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.facebook.com/SMN.ar/videos/mendoza-esta-tarde-se-registr%C3%B3-un-tornado-en-malarg%C3%BCe-en-medio-del-desarrollo-de/668548814847525/'>[1]:<i>Servicio Meteorológico Nacional- Argentina</i> | facebook</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2022_12_27_9999 = L.polyline([[-16.461, -68.175],[-16.461, -68.175]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2022/12/27</h2></th></tr> <tr><th>Start time</th><td>Martes, 27 diciembre 2022</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://abc7.com/post/bolivia-rope-tornado-caught-on-video-el-alto-thunderstorm-in-bolivian-city/12624377/'>[1]:abc 7</a>;<br> <a target='_blank' href='https://www.reddit.com/r/tornado/comments/1dlfrtw/tornado_in_el_alto_bolivia_in_2022/'>[2]:Andylbanez | reddit</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);