const tornado_2017_01_02_9999 = L.polyline([[-35.974, -62.733],[-35.974, -62.733]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/01/02</h2></th></tr> <tr><th>Start time</th><td>Lunes, 2 enero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_01_04_9999 = L.polyline([[-17.75, -46.18],[-17.75, -46.18]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2017/01/04</h2></th></tr> <tr><th>Start time</th><td>Na tarde de quarta-feira, 4 janeiro 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://www.facebook.com/tornadosnobrasil/videos/tornado-minas-gerais-duas-forma%C3%A7%C3%B5es-de-tornados-landspout-foram-registrados-na-t/1049038008557864/'>[1]:<i>Meteorologia Brasil</i> | facebook</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_01_08_9999 = L.polyline([[-34.497, -61.542],[-34.497, -61.542]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/01/08</h2></th></tr> <tr><th>Start time</th><td>Domingo, 8 enero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_01_09_9999_01 = L.polyline([[-32.772, -65.365],[-32.772, -65.365]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/01/09</h2></th></tr> <tr><th>Start time</th><td>Lunes, 9 enero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_01_09_9999_02 = L.polyline([[-32.734, -65.290],[-32.734, -65.290]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2017/01/09</h2></th></tr> <tr><th>Start time</th><td>Lunes, 9 enero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://tn.com.ar/videos/sociedad/el-tornado-de-tilsarao-tn-y-la-gente_765254/'>[1]:TN</a>;<br> <a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[2]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td>Location relative to Tilisarao is not known.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_01_17_9999 = L.polyline([[-36.510, -63.809],[-36.510, -63.809]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/01/17</h2></th></tr> <tr><th>Start time</th><td>Martes, 17 enero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_01_24_9999 = L.polyline([[-27.325, -61.281],[-27.325, -61.281]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/01/24</h2></th></tr> <tr><th>Start time</th><td>Martes, 24 enero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_02_06_9999 = L.polyline([[-37.115, -56.861],[-37.115, -56.861]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/02/06</h2></th></tr> <tr><th>Start time</th><td>Lunes, 6 febrero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_02_23_9999 = L.polyline([[-36.406, -56.943],[-36.406, -56.943]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/02/23</h2></th></tr> <tr><th>Start time</th><td>Jueves, 23 febrero 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_03_12_9999 = L.polyline([[-29.44, -50.58],[-29.44, -50.58]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2017/03/12</h2></th></tr> <tr><th>Start time</th><td>Domingo, 12 março 2017</td></tr> <tr><th>Rating</th><td>F1</td></tr> <tr><th>Mortes</th><td>1</td></tr> <tr><th>Feridos</th><td>70</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://g1.globo.com/rs/rio-grande-do-sul/noticia/2017/03/estragos-em-sao-francisco-de-paula-sao-compativeis-tornado-diz-inmet.html'>[1]:g1</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F1_tornadoes);
const tornado_2017_03_30_9999 = L.polyline([[-27.165, -65.497],[-27.165, -65.497]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/03/30</h2></th></tr> <tr><th>Start time</th><td>Jueves, 30 marzo 2017</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://web.archive.org/web/20260106073015/https://www.ciencias.org.ar/user/Enfoque cientifico del riesgo - evaluacion del potencial de tornados en al republica argentina 2.pdf'>[1]:ENFOQUE CIENTÍFICO DEL RIESGO – EVALUACIÓN DEL POTENCIAL DE TORNADOS EN ARGENTINA (Page 99)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2017_10_19_9999 = L.polyline([[-32.771, -64.094],[-32.771, -64.094]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2017/10/19</h2></th></tr> <tr><th>Start time</th><td>Miércoles, 18 octubre 2017<sup>[2]</sup></td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=9pqhmBhT2MU'>[1]:<i>Telenuevo</i> | YouTube</a>;<br> <a target='_blank' href='https://eldoce.tv/sociedad/los-destrozos-que-dejo-el-tornado-en-rio-cuarto-el-espinillal_52240/'>[2]:eldoce.tv</td></tr> <tr><th>Comments</th><td>Location based on source [2].</td></tr>"
).addTo(F1_tornadoes);
const tornado_2017_12_08_1830 = L.polyline([[-37.368, -58.472],[-37.367, -58.476]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>EF1 Tornado - 2017/12/08</h2></th></tr> <tr><th>Start time</th><td>18:30,<sup>[2]</sup> viernes, 8<sup>[3]</sup> diciembre 2017</td></tr> <tr><th>Rating</th><td>EF0 to EF2<sup>[3]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=iZP6w6OqtBU'>[1]:<i>El Eco de Tandil</i> | YouTube</a>;<br> <a target='_blank' href='https://web.archive.org/web/20201208214633/https://www.youtube.com/watch?v=-WrAnu2P2KU'>[2]:<i>alfredo garnier</i> | YouTube</a>;<br> <a target='_blank' href='https://watchers.news/2017/12/12/impressive-video-of-a-large-tornado-forming-very-close-to-people-argentina/'>[3]:The Watchers</a></td></tr> <tr><th>Comments</th><td><p>Location based on source [2], whose location on Ruta 29 I managed to locate. Path movement is also based on source [2], which seems to show it moving towards Ruta 29 from their left, which is southeast.</p> <p>Source [3] gives windspeed range of 130 to 200 km/h, which yields a central value of 165 km/h, which is EF1.</p></td></tr>"
).addTo(F1_tornadoes);
const tornado_2017_12_08_1830_StartMarker = L.polyline([[-37.368, -58.472],[-37.368, -58.472]], styles_StartMarker).addTo(F1_startMarkers);