const tornado_2021_04_02_9999 = L.polyline([[-35.078, -69.575],[-35.078, -69.575]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2021/04/02</h2></th></tr> <tr><th>Start time</th><td>Viernes, 2<sup>[2]</sup> abril 2021</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=JxPijw4GMu4'>[1]:<i>Meteored</i> | YouTube</a>;<br> <a target='_blank' href='https://www.facebook.com/SMN.ar/videos/tornado-mendoza/2865601230379144/'>[2]:<i>Servicio Meteorológico Nacional- Argentina</i> | facebook</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2021_05_28_9999 = L.polyline([[-27, -51.5],[-27, -51.5]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2021/05/28</h2></th></tr> <tr><th>Start time</th><td>Sexta-feira, 28 maio 2021</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://www.canalenergia.com.br/noticias/53175326/sistema-eletrico-que-alimenta-o-meio-oeste-de-santa-catarina-e-100-restabelecido'>[1]:CanalEnergia</a></td></tr> <tr><th>Comments</th><td>No exact location can be found, only the <i>''Midwest of Santa Catarina''</i>.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2021_09_13_2300 = L.polyline([[-27.119, -52.782],[-27.119, -52.782]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2021/09/13</h2></th></tr> <tr><th>Start time</th><td>23:00, segunda-feira, 13 setembro 2021</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://web.archive.org/web/20260519090819/https://distantreader.org/stacks/journals/bcs/bcs-79.pdf'>[1]:Vortex Storms in the West of Santa Catarina | The Distant Reader</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2021_10_19_9999 = L.polyline([[-12.73, -60.13],[-12.73, -60.13]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2021/10/19</h2></th></tr> <tr><th>Start time</th><td>Terça-feira, 19 outubro 2021</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://prevots.org/prets/mapas_registros/'>[1]:PREVOTS</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2021_10_27_9999 = L.polyline([[-23.42, -51.94],[-23.42, -51.94]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2021/10/27</h2></th></tr> <tr><th>Start time</th><td>Quarta-feira, 27 outubro 2021</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://prevots.org/prets/mapas_registros/'>[1]:PREVOTS</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2021_10_28_9999 = L.polyline([[-8.763, -63.882],[-8.763, -63.882]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2021/10/28</h2></th></tr> <tr><th>Start time</th><td>Quinta-feira, 28 outubro 2021</td></tr> <tr><th>Rating</th><td>F0</td></tr> <tr><th>Mortes</th><td>0</td></tr> <tr><th>Ferimentos</th><td>0</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://revistacenarium.com.br/en/video-unusual-in-amazon-tornado-hits-rondonia-causes-damage-and-scares-residents/'>[1]:REVISTA CENARIUM</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F0_tornadoes);
const tornado_2021_11_17_9999_01 = L.polyline([[-16.481, -68.319],[-16.481, -68.319]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2021/11/17</h2></th></tr> <tr><th>Start time</th><td>Miércoles, 17 noviembre 2021</td></tr> <tr><th>Vientos</th><td>70 to 80 km/h</td></tr> <tr><th>Muertes</th><td>1</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.opinion.com.bo/articulo/pais/tornado-35-familias-damnificadas-gobierno-envia-ayuda-humanitaria/20211118101613843602.html'>[1]:Opinión</a></td></tr> <tr><th>Comments</th><td>Judging by the image from source [1], this could have been a landspout.<br><br> This may have been the same tornado/landspout as the one in Monje Campero, El Alto.</td></tr>"
).addTo(F0_tornadoes);
const tornado_2021_11_17_9999_02 = L.polyline([[-16.501, -68.133],[-16.501, -68.133]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2021/11/17</h2></th></tr> <tr><th>Start time</th><td>Miércoles, 17 noviembre 2021</td></tr> <tr><th>Vientos</th><td>70 to 80 km/h</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.opinion.com.bo/articulo/pais/tornado-ocasiona-destrozos-viviendas-alto-laja/20211117152052843498.html'>[1]:Opinión</a></td></tr> <tr><th>Comments</th><td>This may have been the same tornado/landspout as the F0 in Capacasi. The end of source [1] seems to imply 2 tornadoes: <i>''Meanwhile, the National Meteorology and Hydrology Service (Senamhi) reported that, based on the characteristics of the storms, the winds reached speeds of 70 to 80 kilometers per hour <b>in both cases.</b>''</i></td></tr>"
).addTo(F0_tornadoes);