const tornado_2008_02_01_9999 = L.polyline([[-27.92, -50.10],[-27.92, -50.10]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2008/02/01</h2></th></tr> <tr><th>Start time</th><td>Sexta-feira, 1 fevereiro 2008</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 50)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2008_06_11_9999 = L.polyline([[-30.335, -54.323],[-30.335, -54.323]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2008/06/11</h2></th></tr> <tr><th>Start time</th><td>Quarta-feira, 11 junho 2008</td></tr> <tr><th>Rating</th><td>F0 or F1</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F0_tornadoes);
const tornado_2008_09_05_9999 = L.polyline([[-29.699, -51.687],[-29.699, -51.687]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2008/09/05</h2></th></tr> <tr><th>Start time</th><td>Sexta-feira, 5 setembro 2008</td></tr> <tr><th>Rating</th><td>F1</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td>I found no Coxilha Velha in Rio Grande do Sul province, but I did find a cluster of locations with Coxilha Velha in their name, so I placed this tornado there.</td></tr>"
).addTo(F1_tornadoes);
const tornado_2008_09_11_9999 = L.polyline([[-29.528, -52.127],[-29.528, -52.127]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2008/09/11</h2></th></tr> <tr><th>Start time</th><td>Quinta-feira, 11 setembro 2008</td></tr> <tr><th>Rating</th><td>F1 or F2</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F1_tornadoes);
const tornado_2008_10_26_9999 = L.polyline([[-27.399, -51.224],[-27.399, -51.224]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2008/10/26</h2></th></tr> <tr><th>Start time</th><td>Domingo, 26 outubro 2008</td></tr> <tr><th>Rating</th><td>F0</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F0_tornadoes);
const tornado_2008_11_08_9999 = L.polyline([[-30.340, -50.270],[-30.340, -50.270]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2008/11/08</h2></th></tr> <tr><th>Start time</th><td>Sábado, 8 novembro 2008</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);