const tornado_2007_02_10_9999 = L.polyline([[-26.25, -48.62],[-26.25, -48.62]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2007/02/10</h2></th></tr> <tr><th>Start time</th><td>Sábado, 10 fevereiro 2007</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 50)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2007_02_28_9999 = L.polyline([[-25.000, -53.502],[-25.000, -53.502]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2007/02/28</h2></th></tr> <tr><th>Start time</th><td><span class='source'>14:30,<sup>[1]</sup></span> quarta-feira, 28 fevereiro 2007</td></tr> <tr><th>Windspeed</th><td>146 km/h<sup>[1]</sup></td></tr> <tr><th>Deaths</th><td>0<sup>[1]</sup></td></tr> <tr><th>Injuries</th><td>0<sup>[1]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://web.archive.org/web/20260517201232/https://www.gazetadopovo.com.br/vida-e-cidadania/tornado-atinge-a-regiao-do-aeroporto-de-cascavel-adxcrtgzbfh95rwjl4jgqh2z2/'>[1]:Gazeta do Povo</a>;<br> <a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[2]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F1_tornadoes);
const tornado_2007_03_18_9999 = L.polyline([[-29.758, -50.018],[-29.758, -50.018]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2007/03/18</h2></th></tr> <tr><th>Start time</th><td>Domingo, 18 março 2007</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2007_07_22_9999 = L.polyline([[-27.684, -48.489],[-27.684, -48.489]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2007/07/22</h2></th></tr> <tr><th>Start time</th><td>Domingo, 22 julho 2007</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2007_09_29_9999 = L.polyline([[-27.782, -52.808],[-27.782, -52.808]], styles_F2).bindPopup(
    "<table><thead><tr><th class='popup_header_F2' colspan=2 style='text-align: center;'><h2>F2 Tornado - 2007/09/29</h2></th></tr> <tr><th>Start time</th><td>Sábado, 29 setembro 2007</td></tr> <tr><th>Rating</th><td>F2</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F2_tornadoes);
const tornado_2007_10_05_9999 = L.polyline([[-24.828, -49.263],[-24.828, -49.263]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2007/10/05</h2></th></tr> <tr><th>Start time</th><td>Sexta-feira, 5 outubro 2007</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 48)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2007_10_28_9999 = L.polyline([[-27.778, -54.236],[-27.778, -54.236]], styles_F2).bindPopup(
    "<table><thead><tr><th class='popup_header_F2' colspan=2 style='text-align: center;'><h2>F2 Tornado - 2007/10/28</h2></th></tr> <tr><th>Start time</th><td>Domingo, 28 outubro 2007</td></tr> <tr><th>Rating</th><td>F2</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F2_tornadoes);
const tornado_2007_11_01_9999_01 = L.polyline([[-27.779, -54.232],[-27.779, -54.232]], styles_F2).bindPopup(
    "<table><thead><tr><th class='popup_header_F2' colspan=2 style='text-align: center;'><h2>F2 Tornado - 2007/11/01</h2></th></tr> <tr><th>Start time</th><td>Quinta-feira, 1 novembro 2007</td></tr> <tr><th>Rating</th><td>F2</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F2_tornadoes);
const tornado_2007_11_01_9999_02 = L.polyline([[-28.721, -49.298],[-28.721, -49.298]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2007/11/01</h2></th></tr> <tr><th>Start time</th><td>Quinta-feira, 1 novembro 2007</td></tr> <tr><th>Rating</th><td>F0</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F0_tornadoes);
const tornado_2007_11_04_9999 = L.polyline([[-26.176, -50.398],[-26.176, -50.398]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2007/11/04</h2></th></tr> <tr><th>Start time</th><td>Domingo, 4 novembro 2007</td></tr> <tr><th>Rating</th><td>F1</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F1_tornadoes);
const tornado_2007_12_25_9999 = L.polyline([[-26.034, -48.853],[-26.034, -48.853]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2007/12/25</h2></th></tr> <tr><th>Start time</th><td>Terça-feira, 25 dezembro 2007</td></tr> <tr><th>Rating</th><td>F0</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://teses.usp.br/teses/disponiveis/90/90131/tde-02052013-160126/publico/DISSERTACAO_BRUNO_BERTONI.pdf'>[1]:ESTUDOS DE CASO DE TORNADOS, USO E OCUPA&#xC7;ÃO DO SOLO, TOPOGRAFIA E ANÁLISE METEOROLÓGICA DESTES EVENTOS ATMOSFÉRICOS NO SUL E SUDESTE DO BRASIL | Universidade de São Paulo (Page 49)</a></td></tr> <tr><th>Comments</th><td>I assume source [1] meant <i>Garuva</i>, since I found no Guaruva in Santa Catarina.</td></tr>"
).addTo(F0_tornadoes);