const tornado_2026_01_01_9999_02 = L.polyline([[-24.453, -54.165],[-24.453, -54.165]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2026/01/01</h2></th></tr> <tr><th>Start time</th><td>Na tarde de jueves, 1 janeiro 2026</td></tr> <tr><th>Windspeed</th><td>120 km/h</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://g1.globo.com/pr/oeste-sudoeste/noticia/2026/01/02/video-tornados-sao-registrados-no-parana-com-ventos-de-120-kmh.ghtml'>[1]:g1</a>;<br> <a target='_blank' href='https://www.parana.pr.gov.br/aen/Noticia/Apos-classificacao-de-tornado-em-Mercedes-temporais-dao-tregua-no-Parana-no-fim-de'>[2]:Paraná Governo do Estado</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F1_tornadoes);
const tornado_2026_01_09_9999 = L.polyline([[-31.898, -64.774],[-31.898, -64.774]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/01/09</h2></th></tr> <tr><th>Start time</th><td>Na manhã de sexta-feira, 9 janeiro 2026</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://www.lavoz.com.ar/servicios/en-medio-de-las-lluvias-el-extrano-fenomeno-en-el-cielo-que-preocupo-a-vecinos-de-la-cumbrecita/'>[1]:La Voz</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_01_10_9999_01 = L.polyline([[-25.4762, -49.1480],[-25.4844, -49.1435]], styles_F2).bindPopup(
    "<table><thead><tr><th class='popup_header_F2' colspan=2 style='text-align: center;'><h2>F2 Tornado - 2026/01/10</h2></th></tr> <tr><th>Start time</th><td>Sábado, 10 janeiro 2026</td></tr> <tr><th>Rating</th><td>F2<sup>[2]</sup></td></tr> <tr><th>Length</th><td>1 km<sup>[4]</sup></td></tr> <tr><th>Deaths</th><td>0</td></tr> <tr><th>Injuries</th><td>2<sup>[2][3]</sup></td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://www.metropoles.com/brasil/tornado-sao-jose-dos-pinhais-sjp-parana'>[1]:Metrópoles</a>;<br> <a target='_blank' href='https://g1.globo.com/pr/parana/noticia/2026/01/11/tornado-em-sao-jose-dos-pinhais-estragos.ghtml'>[2]:g1</a>;<br> <a target='_blank' href='https://web.archive.org/web/20260517163425/https://www.defesacivil.pr.gov.br/Noticia/Simepar-classifica-tornado-que-atingiu-Sao-Jose-dos-Pinhais-na-categoria-F2-da-Escala'>[3]:COORDENADORIA ESTADUAL DE DEFESA CIVIL</a>;<br> <a target='_blank' href='https://g1.globo.com/pr/parana/noticia/2026/01/11/tornado-em-sao-jose-dos-pinhais-classificacao.ghtml'>[4]:g1</a>;<br> <a target='_blank' href='https://agenciabrasil.ebc.com.br/radioagencia-nacional/meio-ambiente/audio/2026-01/tornado-danificou-350-casas-em-sao-jose-dos-pinhais-pr'>[5]:radioagência</a></td></tr> <tr><th>Comments</th><td>Tornado's location in Guatupê, São José dos Pinhais, was found using a photograph from source [3], which shows a destroyed wall which used to run along a brick road, with some white buildings in the background. I placed this tornado's path's center at the location where this photograph was taken. Tornado movement direction is based on this statement from source [4]: <i>''The most severe storm cell developed in the late afternoon over Almirante Tamandaré and Colombo, moved over Curitiba causing intense winds and hail, and went as far as São José dos Pinhais.''</i></td></tr>"
).addTo(F2_tornadoes);
const tornado_2026_01_10_9999_01_StartMarker = L.polyline([[-25.4762, -49.1480],[-25.4762, -49.1480]], styles_StartMarker).addTo(F2_startMarkers);
const tornado_2026_01_12_9999 = L.polyline([[-26.185, -50.690],[-26.185, -50.690]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/01/12</h2></th></tr> <tr><th>Start time</th><td>Monday, 12 janeiro 2026</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://metsul.com/serie-de-tornados-surpreende-o-sul-do-brasil-no-inicio-de-2026/'>[1]:Metsul</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_02_07_1356 = L.polyline([[-25.586, -54.513],[-25.586, -54.513]], styles_F0).bindPopup(
    "<table><thead><tr><th class='popup_header_F0' colspan=2 style='text-align: center;'><h2>F0 Tornado - 2026/02/12</h2></th></tr> <tr><th>Start time</th><td>13:56, Saturday, 7 fevereiro 2026</td></tr> <tr><th>Rating</th><td>F0</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://g1.globo.com/pr/oeste-sudoeste/noticia/2026/02/09/video-moradores-de-foz-do-iguacu-se-escondem-atras-de-carro-enquanto-tornado-arranca-telhado-de-casa.ghtml'>[1]:g1</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F0_tornadoes);
const tornado_2026_02_12_1045 = L.polyline([[-31.751, -52.378],[-31.751, -52.378]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/02/12</h2></th></tr> <tr><th>Start time</th><td>10:45,<sup>[2]</sup> Thursday, 12 fevereiro 2026</td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://www.infomoney.com.br/brasil/rs-registra-2-tornados-em-4-dias-e-defesa-civil-mantem-alerta-para-tempestades/'>[1]:InfoMoney</a>;<br> <a target='_blank' href='https://www.metropoles.com/brasil/tornado-atinge-cidade-no-rio-grande-do-sul-com-ventos-de-75-km-h'>[2]:Metrópoles</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_02_15_1835 = L.polyline([[-30.790, -52.628],[-30.790, -52.628]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/02/15</h2></th></tr> <tr><th>Start time</th><td>18:35, Sunday, 15 fevereiro 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://g1.globo.com/rs/rio-grande-do-sul/noticia/2026/02/16/tornado-no-interior-do-rs-encruzilhada-do-sul.ghtml'>[1]:g1</a>;<br> <a target='_blank' href='https://www.infomoney.com.br/brasil/rs-registra-2-tornados-em-4-dias-e-defesa-civil-mantem-alerta-para-tempestades/'>[2]:InfoMoney</a></td></tr> <tr><th>Comments</th><td>Location is based on it being filmed from Arroio Abranjo.<sup>[1]</sup></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_02_23_9999_02 = L.polyline([[-27.70, -66.01],[-27.70, -66.01]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2026/02/23</h2></th></tr> <tr><th>Start time</th><td>La tarde de lunes, 23 fevereiro 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Deaths</th><td>0</td></tr> <tr><th>Injuries</th><td>0</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://www.clarin.com/sociedad/sorpresivo-tornado-asusto-catamarca-fenomeno-origino-zona-rural-aconquija_0_dKJBjQxc4V.html'>[1]:Clárin</a>;<br> <a target='_blank' href='https://www.facebook.com/Cadena3Argentina/videos/%EF%B8%8F-un-tornado-sorprendi%C3%B3-a-catamarcaun-fen%C3%B3meno-meteorol%C3%B3gico-poco-habitual-gener/1207071848260615/'>[2]:<i>Cadena 3 Argentina</i> | facebook</a>;<br> <a target='_blank' href='https://www.instagram.com/reel/DVJBM-rkdtk/'>[3]:<i>multivisionfederalok</i> | Instagram</a>;<br> <a target='_blank' href='https://web.archive.org/web/20260309010836/https://www.infobae.com/sociedad/2026/02/24/video-un-remolino-de-viento-sorprendio-a-los-vecinos-de-una-localidad-rural-en-catamarca/'>[4]:infobae</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_03_11_1830 = L.polyline([[-38.044, -67.920],[-38.044, -67.920]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2026/03/11</h2></th></tr> <tr><th>Start time</th><td>18:30, miércoles, 11 marzo 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://www.facebook.com/100063519664162/videos/%EF%B8%8Ftornado-registrado-en-el-l%C3%ADmite-de-r%C3%ADo-negro-y-la-pampa-ruta-151-entre-25-de-ma/2085120818886392/'>[2]:<i>RadioCentro - Villa Huidobro</i> | facebook</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_03_28_0500 = L.polyline([[-33.46, -61.32],[-33.46, -61.32]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/03/28</h2></th></tr> <tr><th>Start time</th><td>05:00<sup>[1][2]</sup> or 06:00<sup>[4]</sup>, sábado, 28 marzo 2026</td></tr> <tr><th>Rating</th><td>? (described as violent)</td></tr> <tr><th>Muertes</th><td>1<sup>[4]</sup></td></tr> <tr><th>Injuries</th><td>0<sup>[3]</sup></td></tr> <tr><th>Sources</th><td><a target='_blank' href='https://www.eldiariodelapampa.com.ar/pais/71779/un-tornado-causo-estragos-en-el-sur-de-santa-fe-y-dejo-a-la-localidad-de-bombal-sin-luz'>[1]:El Diario de la Pampa</a>;<br> <a target='_blank' href='https://www.elesquiu.com/nacionales/2026/3/29/un-tornado-arraso-el-sur-de-santa-fe-dejo-bombal-sin-luz-591389.html'>[2]:El Esquiú</a>;<br> <a target='_blank' href='https://www.analisisdigital.com.ar/interes-general/2026/03/29/un-tornado-destruyo-una-planta-de-acopio-y-genero-graves-danos-en-una-localidad-santafesina'>[3]:Análisis</a>;<br> <a target='_blank' href='https://www.elancasti.com.ar/informacion-general/feroz-temporal-dejo-un-muerto-y-graves-destrozos-santa-fe-n609055'>[4]:El Ancasti</a></td></tr> <tr><th>Comments</th><td>Sources [1] & [2] have extremely similar details, & since [1] published their article 6 hours before [2] did, [2] probably copied [1].</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_05_06_1800 = L.polyline([[-35.940,-59.373],[-35.955,-59.321],[-36.016,-59.237],[-36.034,-59.209],[-36.057,-59.186]], styles_F3).bindPopup(
    "<table><thead><tr><th class='popup_header_F3' colspan=2 style='text-align: center;'><h2>IF3 Tornado - 2026/05/06</h2></th></tr> <tr><th>Start time</th><td>18:00,<sup>[5]</sup> miércoles, 6 mayo 2026</td></tr> <tr><th>Rating</th><td>IF3<sup>[8]</sup></td></tr> <tr><th>Largo</th><td>20 km<sup>[8]</sup></td></tr> <tr><th>Heridos</th><td>4</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.infobae.com/sociedad/2026/05/07/se-nos-cayo-la-casa-arriba-el-dramatico-relato-de-la-familia-de-las-flores-que-perdio-su-hogar-por-un-tornado/'>[1]:infobae</a>;<br> <a target='_blank' href='https://cdnoticias.com/index.php/2026/05/07/tornado-en-las-flores-afecto-zonas-rurales-y-aseguran-que-fue-de-nivel-f2/'>[2]:Central de Noticias</a>;<br> <a target='_blank' href='https://www.lmneuquen.com/pais/un-tornado-destruyo-una-vivienda-genero-destrozos-y-dejo-una-ciudad-oscuras-n1237704'>[3]:LM Neuquen</a>;<br> <a target='_blank' href='https://www.clarin.com/sociedad/impactante-tornado-azoto-flores-destruyo-casa-dejo-heridos-gran-parte-ciudad-quedo-luz_0_KK7IGE4Rnb.html'>[4]:Clarín</a>;<br> <a target='_blank' href='https://www.youtube.com/watch?v=VWgjQy4rtvA'>[5]:<i>Crónica TV</i> | YouTube</a>;<br> <a target='_blank' href='https://www.google.com/maps/d/u/0/viewer?mid=1miZM6oOopquzYHV6op98x6vzhEq3Dlw'>[6]:<i>Tornados en Argentina</i> | Google My Maps</a>;<br> [7]:<a target='_blank' href='https://browser.dataspace.copernicus.eu/'>Sentinel-2</a> satellite-imagery;<br> <a target='_blank' href='https://drive.google.com/file/d/1jU5yU_1zHx6NiZXRU44D7atOCfx8DoIb/view?pli=1'>[8]:Informe técnico del relevamiento de daños asociado al tornado ocurrido en Las Flores, provincia de Buenos Aires, el 6 de mayo de 2026 | Google Drive</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(F3_tornadoes);
const tornado_2026_05_06_1800_StartMarker = L.polyline([[-35.940,-59.373],[-35.940,-59.373]], styles_StartMarker).addTo(F3_startMarkers);
const tornado_2026_05_07_9999 = L.polyline([[-26.928, -58.509],[-26.928, -58.509]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/05/07</h2></th></tr> <tr><th>Start time</th><td>La tarde de jueves, 7 mayo 2026<sup>[2]</sup></td></tr> <tr><th>Rating</th><td>Unrated</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/shorts/sJua-TWTB3c'>[1]:<i>josé Godoy</i> | YouTube</a>;<br> <a target='_blank' href='https://www.facebook.com/MunicipalidaddePuertoBermejo/videos/tras-el-fuerte-temporal-y-tornadoocurrido-en-la-tarde-de-ayerjueves-7-de-mayo-en/844492558706672/'>[2]:<i>Municipalidad de Puerto Bermejo</i> | facebook</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_12_1500 = L.polyline([[-18.781, -52.906],[-18.795, -52.894]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/12</h2></th></tr> <tr><th>Start time</th><td>15:00, sexta-feira, 12 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Longa</th><td>2 km<sup>[1]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net. See also <a target='_blank' href='images/tornadoes_Goiás_20260612-20260623.png'>this image from source 1</a>.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_12_1500_StartMarker = L.polyline([[-18.781, -52.906],[-18.781, -52.906]], styles_StartMarker).addTo(FU_startMarkers);
const tornado_2026_06_14_0800 = L.polyline([[-18.194, -50.853],[-18.190, -50.835]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/14</h2></th></tr> <tr><th>Start time</th><td>08:00, domingo, 14 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Longa</th><td>2 km<sup>[1]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net. See also <a target='_blank' href='images/tornadoes_Goiás_20260612-20260623.png'>this image from source 1</a>.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_14_0800_StartMarker = L.polyline([[-18.194, -50.853],[-18.194, -50.853]], styles_StartMarker).addTo(FU_startMarkers);
const tornado_2026_06_14_2000 = L.polyline([[-18.105, -50.781],[-18.1029, -50.7558]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/14</h2></th></tr> <tr><th>Start time</th><td>20:00, domingo, 14 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Longa</th><td>2.5 km<sup>[1]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net. See also <a target='_blank' href='images/tornadoes_Goiás_20260612-20260623.png'>this image from source 1</a>.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_14_2000_StartMarker = L.polyline([[-18.105, -50.781],[-18.105, -50.781]], styles_StartMarker).addTo(FU_startMarkers);
const tornado_2026_06_23_0800 = L.polyline([[-17.692, -52.218],[-17.708, -52.207],[-17.719, -52.203]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/23</h2></th></tr> <tr><th>Start time</th><td>08:00, terça-feira, 23 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Longa</th><td>3.5 km<sup>[1]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net. See also <a target='_blank' href='images/tornadoes_Goiás_20260612-20260623.png'>this image from source 1</a>.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_23_0800_StartMarker = L.polyline([[-17.692, -52.218],[-17.692, -52.218]], styles_StartMarker).addTo(FU_startMarkers);
const tornado_2026_06_28_2000 = L.polyline([[-24.672, -52.566],[-24.672, -52.566]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/28</h2></th></tr> <tr><th>Start time</th><td>20:00, domingo, 28 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_28_2300 = L.polyline([[-24.561, -50.865],[-24.560, -50.845],[-24.540, -50.802]], styles_F2).bindPopup(
    "<table><thead><tr><th class='popup_header_F2' colspan=2 style='text-align: center;'><h2>F2 Tornado - 2026/06/28</h2></th></tr> <tr><th>Start time</th><td>23:00,<sup>[3][4]</sup> domingo, 28 junho 2026</td></tr> <tr><th>Ventos</th><td>200 km/h<sup>[1]</sup></td></tr> <tr><th>Longa</th><td>7 km<sup>[4]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://www.parana.pr.gov.br/aen/Noticia/Simepar-confirma-tornado-da-categoria-F2-em-Reserva-ventos-chegaram-200-kmh'>[1]:Paraná Governo do Estado</a>;<br> <a target='_blank' href='https://g1.globo.com/pr/campos-gerais-sul/noticia/2026/07/01/meteorologistas-confirmam-novo-tornado-no-parana.ghtml'>[2]:g1</a>;<br> <a target='_blank' href='https://www.instagram.com/p/DaQOSE-RAHX/'>[3]:<i>beltraoagora</i> | Instagram</a>;<br> <a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[4]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net.</td></tr>"
).addTo(F2_tornadoes);
const tornado_2026_06_28_2300_StartMarker = L.polyline([[-24.561, -50.865],[-24.561, -50.865]], styles_StartMarker).addTo(F2_startMarkers);
const tornado_2026_06_29_0800 = L.polyline([[-24.034, -53.492],[-24.031, -53.488]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/29</h2></th></tr> <tr><th>Start time</th><td>08:00, segunda-feira, 29 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Longa</th><td>600 m<sup>[1]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_29_0800_StartMarker = L.polyline([[-24.034, -53.492],[-24.034, -53.492]], styles_StartMarker).addTo(FU_startMarkers);
const tornado_2026_06_30_1500_01 = L.polyline([[-25.687, -51.136],[-25.694, -51.097],[-25.696, -51.064],[-25.730, -51.005]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/30</h2></th></tr> <tr><th>Start time</th><td>15:00<sup>[3]</sup> or 20:00,<sup>[1]</sup> terça-feira, 30 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Longa</th><td>14.5 km<sup>[3]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://folhadeirati.com.br/video-impressionante-tornado-e-registrado-em-inacio-martins-e-deixa-rastro-de-destruicao-na-divisa-com-cruz-machado/'>[1]:Folha de Irati</a>;<br> <a target='_blank' href='https://najua.com.br/noticia/possivel-tornado-e-analisado-pelo-simepar-apos-temporal-em-inacio-martins/'>[2]:Najuá</a>;<br> <a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[3]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td>Movement direction confirmed using earth.nullschool.net.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_30_1500_01_StartMarker = L.polyline([[-25.687, -51.136],[-25.687, -51.136]], styles_StartMarker).addTo(FU_startMarkers);
const tornado_2026_06_30_1500_02 = L.polyline([[-25.204, -53.155],[-25.204, -53.155]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/30</h2></th></tr> <tr><th>Start time</th><td>15:00, terça-feira, 30 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_30_1500_03 = L.polyline([[-25.570, -51.077],[-25.570, -51.077]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/30</h2></th></tr> <tr><th>Start time</th><td>15:00, terça-feira, 30 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_06_30_1630 = L.polyline([[-25.044, -51.528],[-25.044, -51.528]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2026/06/30</h2></th></tr> <tr><th>Start time</th><td>16:30, terça-feira, 30 junho 2026</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://samhi.cima.fcen.uba.ar/'>[1]:Base de Datos de Amenazas Meteorológicas y sus Impactos de América del Sur</a>;<br> <a target='_blank' href='https://www.instagram.com/reel/DaOxKsgs4TA/'>[2]:<i>santacatarinaemfotosbr</i> | Instagram</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2026_07_21_9999 = L.polyline([[-27.386, -53.959],[-27.389, -53.950]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>Tornado - 2026/07/21</h2></th></tr> <tr><th>Start time</th><td>Na tarde de terça-feira, 21 julho 2026</td></tr> <tr><th>Rating</th><td>F1 or F2<sup class='M' title='This rating is based on damage-photos from sources [2] & [3].'>[M]</sup></td></tr> <tr><th>Longa</th><td>?</td></tr> <tr><th>Mortes</th><td>0<sup>[2]</sup></td></tr> <tr><th>Ferimentos</th><td>0<sup>[2]</sup></td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://www.facebook.com/nossaterranossagenters/videos/tornado-atinge-localidades-do-interior-de-tr%C3%AAs-passos-rs-e-mobiliza-defesa-civil/1068853369158181/'>[1]:<i>NOSSA TERRA NOSSA GENTE</i> | facebook</a>;<br> <a target='_blank' href='https://web.archive.org/web/20260722105355/https://www.clicportela.com.br/noticia/172987/tornado-provoca-destelhamentos-queda-de-arvores-e-deixa-comunidades-sem-energia-em-tres-passos'>[2]:Sistema provincia</a>;<br> <a target='_blank' href='https://web.archive.org/web/20260722105549/https://radioaltouruguai.com.br/municipio-de-tres-passos-relata-diversos-danos-em-razao-da-forte-tempestade-ocorrida-na-terca-feira/'>[3]:Rádio Alto Uruguai</a></td></tr> <tr><th>Comments</th><td>Path based on damage-photos from source [3]; actual length unknown. Movement direction based on earth.nullschool.net.</td></tr>"
).addTo(F1_tornadoes);
const tornado_2026_07_21_9999_StartMarker = L.polyline([[-27.386, -53.959],[-27.386, -53.959]], styles_StartMarker).addTo(F1_startMarkers);