const tornado_2024_01_09_9999 = L.polyline([[-32.69, -63.44],[-32.69, -63.44]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2024/01/09</h2></th></tr> <tr><th>Start time</th><td>Martes, 9 enero 2024</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=oj6eprR3lvU&t=67s'>[1]:<i>Ignacio Bergara | Meteorología</i> | YouTube (1:07)</a></td></tr> <tr><th>Comments</th><td>Did not directly impact Ticino, but location relative to Ticino is not known. No damage was caused.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2024_01_15_9999 = L.polyline([[-26.54, -56.92],[-26.54, -56.92]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2024/01/15</h2></th></tr> <tr><th>Start time</th><td>La tarde de lunes, 15 enero 2024</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.ultimahora.com/reportan-un-embudo-de-tornado-en-misiones'>[1]:ÚltimaHora</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2024_02_22_9999 = L.polyline([[-9.39, -36.76],[-9.39, -36.76]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>F1 Tornado - 2024/02/22</h2></th></tr> <tr><th>Start time</th><td>Na tarde de quinta-feira, 22 fevereiro 2024</td></tr> <tr><th>Rating</th><td>F1</td></tr> <tr><th>Fontes</th><td><a target='_blank' href='https://web.archive.org/web/20240223021726/https://metsul.com/raro-tornado-provoca-estragos-no-interior-do-nordeste-do-brasil/'>[1]:Metsul</a></td></tr> <tr><th>Comments</th><td>Location relative to Estrela de Alagoas in not known.</td></tr>"
).addTo(F1_tornadoes);
const tornado_2024_04_03_9999 = L.polyline([[-23.32, -64.22],[-23.32, -64.22]], styles_F1).bindPopup(
    "<table><thead><tr><th class='popup_header_F1' colspan=2 style='text-align: center;'><h2>EF1 Landspout - 2024/04/03</h2></th></tr> <tr><th>Start time</th><td>Miércoles, 3 abril 2024<sup>[1]</sup></td></tr> <tr><th>Rating</th><td>EF1</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=oj6eprR3lvU&t=86s'>[1]:<i>Ignacio Bergara | Meteorología</i> | YouTube (1:26)</a>;<br> <a target='_blank' href='https://www.tiktok.com/@storms.in.the.world/video/7539035080149241093'>[2]:<i>storm.in.the.world</i> | TikTok</a></td></tr> <tr><th>Comments</th><td>I am mildly skeptical of the EF1 rating claimed by source [2], but I do trust it enough.</td></tr>"
).addTo(F1_tornadoes);
const tornado_2024_09_20_9999 = L.polyline([[-16.474, -68.189],[-16.474, -68.189]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2024/09/20</h2></th></tr> <tr><th>Start time</th><td>Viernes, 20 septiembre 2024</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.opinion.com.bo/articulo/pais/tornado-azota-laja-vientos-huracanados-impactan-sena/20240925000007956449.html'>[1]:Opinión</a></td></tr> <tr><th>Comments</th><td></td></tr>"
).addTo(FU_tornadoes);
const tornado_2024_10_16_9999 = L.polyline([[-37.342, -67.643],[-37.342, -67.643]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2024/10/16</h2></th></tr> <tr><th>Start time</th><td>Miércoles, 16 octubre 2024</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.losandes.com.ar/sociedad/viento-lluvias-granizo-y-un-tornado-en-la-pampa'>[1]:Los Andes</a>;<br> <a target='_blank' href='https://www.lateclamardelplata.com.ar/53272-un-tornado-en-la-pampa'>[2]:La Tecla Mar del Plata</a></td></tr> <tr><th>Comments</th><td>Managed to locate the road in the video from source [2] (roughly south of the tornado), after which I placed the tornado roughly where it seemed to be in the video.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2024_10_22_9999 = L.polyline([[-32.65, -62.12],[-32.65, -62.12]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2024/10/22</h2></th></tr> <tr><th>Start time</th><td>La tarde del martes, 22 octubre 2024<sup>[2]</sup></td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=oj6eprR3lvU&t=118s'>[1]:<i>Ignacio Bergara | Meteorología</i> | YouTube (1:58)</a>;<br> <a target='_blank' href='https://www.facebook.com/LaVoz.com.ar/videos/-tornado-en-marcos-ju%C3%A1reztal-como-lo-anunci%C3%B3-el-servicio-meteorol%C3%B3gico-nacional-/830962785607818/'>[2]:<i>LaVoz.com.ar</i> | facebook</a></td></tr> <tr><th>Comments</th><td><p>Source [2] confirms that this was a landspout. Source [2] also confirms that this tornado occurred on 22 octubre instead of 23 octubre, since it was posted on 22 octubre.</p> <p>Location was found by locating where the video was taken & what direction they were filming, along with source [2] stating it occurred around 5 kilometers away from Marcos Juárez.</p></td></tr>"
).addTo(FU_tornadoes);
const tornado_2024_10_25_9999 = L.polyline([[-32.5, -58.5],[-32.5, -58.5]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Landspout - 2024/10/25</h2></th></tr> <tr><th>Start time</th><td>Viernes, 25 octubre 2024</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=oj6eprR3lvU&t=132s'>[1]:<i>Ignacio Bergara | Meteorología</i> | YouTube (2:12)</a>;<br> <a target='_blank' href='https://www.instagram.com/reel/DBkDGRZhjnO/'>[2]:<i>smn_argentina</i> | Instagram</a></td></tr> <tr><th>Comments</th><td>No location other than Uruguay department, Entre Ríos, is given.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2024_12_11_9999 = L.polyline([[-39.30, -65.76],[-39.30, -65.76]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2024/12/11</h2></th></tr> <tr><th>Start time</th><td>Miércoles, 11 diciembre 2024</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=oj6eprR3lvU&t=182s'>[1]:<i>Ignacio Bergara | Meteorología</i> | YouTube (3:02)</a></td></tr> <tr><th>Comments</th><td>Location relative to Luis Beltrán is not known.</td></tr>"
).addTo(FU_tornadoes);
const tornado_2024_12_19_9999 = L.polyline([[-37.85, -58.25],[-37.85, -58.25]], styles_FU).bindPopup(
    "<table><thead><tr><th class='popup_header_FU' colspan=2 style='text-align: center;'><h2>Tornado - 2024/12/19</h2></th></tr> <tr><th>Start time</th><td>Jueves, 19 diciembre 2024</td></tr> <tr><th>Rating</th><td>?</td></tr> <tr><th>Fuentes</th><td><a target='_blank' href='https://www.youtube.com/watch?v=oj6eprR3lvU&t=192s'>[1]:<i>Ignacio Bergara | Meteorología</i> | YouTube (3:12)</a></td></tr> <tr><th>Comments</th><td>Location relative to Balcarce is not known.</td></tr>"
).addTo(FU_tornadoes);